name: CI/CD Pipeline

on:
  push:
    branches:
      - dev       # development
      - test      # business testing
      - main      # production

jobs:
  dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to DEV via SSH (No Docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /mnt/data/sujalmh/vr
            git pull origin dev
            fuser -k 8050/tcp || true
            fuser -k 8060/tcp || true

            cd loader
            source venv/bin/activate
            pip install -r requirements.txt
            nohup uvicorn main:app --host 0.0.0.0 --port 8050 > loader.log 2>&1 &
            deactivate

            cd ../retrieval
            source venv/bin/activate
            pip install -r requirements.txt
            nohup uvicorn main:app --host 0.0.0.0 --port 8060 > retrieval.log 2>&1 &
            deactivate

  test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to TEST
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /mnt/data/sujalmh/vr
            git pull origin test
            bash deploy.sh loader test 8051
            bash deploy.sh retrieval test 8061

  prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /mnt/data/sujalmh/vr
            git pull origin main
            bash deploy.sh loader prod 8053
            bash deploy.sh retrieval prod 8063
